### ISSUE TITLE
ReStock Whitelist

### ISSUE THREAD

**Issue by hemeac** [JadeOfMaar/AirlineKuisine#7]
Came across two parts that need to have models whitelisted when ReStock is installed:

ds00_pres_srf1
ds00_pres_250

This is what my logfile noted was missing, adding them to the whitelist fixed the issue:

Squad/Parts/FuelTank/Size3Tanks/Size3SmallTank
Squad/Parts/FuelTank/RCStankRadialLong/model

Edit: Apologies, believe these are DeepSky Core

**Comment by JadeOfMaar** [comment]
I've published an update with this fix. 😃
